In [52]:
import numpy as np
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.structure import Structure
from mp_api.client import MPRester
from jupyter_jsmol import JsmolView
from jupyter_jsmol.pymatgen import quick_view

In [53]:
mp_key = "fShF0m8lEepeLAjHYRHR50cMgpJGq7yr"
mp_id = "mp-16763"

In [54]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [55]:
atoms_indices = [2, 5, 8] 
symmetry_ops = [symmops[3], symmops[10], symmops[20]]  

for i, symmop in enumerate(symmetry_ops):
    print(f"Symétrie {i+1}:")
    print(symmop)
    print()

Symétrie 1:
Rot:
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]

Symétrie 2:
Rot:
[[-1.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]

Symétrie 3:
Rot:
[[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0.66666667 0.33333333 0.33333333]



In [56]:
# Création d'une liste pour stocker les nouvelles positions des atomes
transformed_positions = []

for i in range(3):  # On applique une transformation par atome
    original_coords = conv_struc[atoms_indices[i]].frac_coords  # Coordonnées initiales
    transformed_coords = symmetry_ops[i].operate(original_coords)  # Application de la transformation
    
    transformed_positions.append(transformed_coords)
    print(f"Atome {atoms_indices[i]} :")
    print(f"  Coordonnées initiales : {original_coords}")
    print(f"  Coordonnées transformées : {transformed_coords}\n")

Atome 2 :
  Coordonnées initiales : [0.66666667 0.33333333 0.83333333]
  Coordonnées transformées : [ 0.33333333 -0.33333333 -0.83333333]

Atome 5 :
  Coordonnées initiales : [0.33333333 0.66666667 0.66666667]
  Coordonnées transformées : [-0.33333333  0.33333333 -0.66666667]

Atome 8 :
  Coordonnées initiales : [0.66666667 0.33333333 0.59667508]
  Coordonnées transformées : [ 1.          0.         -0.26334175]



In [57]:
# Visualisation de la structure originale
print("Structure originale :")
view_orig = quick_view(conv_struc, "packed", conventional=True)
display(view_orig)

Structure originale :


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [58]:
# Création d'une structure modifiée
modified_structure = conv_struc.copy()
for i in range(3):
    modified_structure.append("Si", transformed_positions[i], coords_are_cartesian=False)  # Remplace "X" par un élément valide

# Visualisation de la structure transformée
print("Structure après transformation :")
view_transformed = quick_view(modified_structure, "packed", conventional=True)
display(view_transformed)

Structure après transformation :


JsmolView(layout=Layout(align_self='stretch', height='400px'))